openapi: '3.0.2'
info:
  title: Salle De Chinema
  description: Calendrier hebdomadaire projection
  version: '1.0.0'
servers:
  - url: https://STD21005.com
paths:
  /Film:
    get:
      tags:
        - "Film"
      summary: get all Film
      operationId: getFilm
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: page Size
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: list of Film
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Projection'
        '400':
          description: bad request
    post:
      tags:
        - "Film"
      summary: Add new Film
      operationId: AddFilm
      description: Add new Film
      requestBody:
        description: Film to be Added
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Film'
        required: true
      responses:
        '200':
         description: list of Film
         content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateFilm'
        '400':
          description: bad request
    put:
      tags:
        - Film
      summary: put new film
      operationId: put film
      parameters:
        - name: titre
          in: query
          schema:
            type: string
          required: true
      requestBody:
        description: Film to be Added
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Projection'
        required: true
      responses:
        '200':
         description: list of Film
         content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Projection'
        '400':
          description: bad request
    
    patch:
      tags:
      - Film
      summary: update a student
      operationId: update a student
      requestBody:
        description: Student to be created
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Film'
            examples:
              changeTitre:
                value:
                  id: 1
                  name: "30jours max"
              changeSalle:
                value:
                  id: 1
                  address: 'B'
              ChangeHeure_diffusion:
                value:
                  id: 1
                  heure: 21Heure
      responses:
        '200':
         description: list of Film
         content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Projection'
        '400':
          description: bad request
  /Film/{id}:         
    delete:
      tags:
        - Film
      summary: delete some Film
      operationId: delete film
      description: deleted
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Film is deleted succefull
          

      
components:
  schemas:
    CreateFilm:
      type: object
      properties:
        id:
          type: integer
        Film:
          type: array
          items:
              $ref: '#/components/schemas/Film'
    Film:
      type: object
      properties:
        titre:
          type: string
        dure:
          type: string
          format: hours
          example: '1hours'
        realisateur:
          type: string
        date_de_sortie:
          type: string
          format: date
          example: '2022-01-01'
        resume:
          type: string
        
          
    Salle:
      type: object
      properties:
        name:
          type: string
          example: "A"
        capacite_accueil:
          type: string
          example: "80"
      
    Projection:
      type: object
      properties:
        id:
          type: number
        film:
          type: object
          $ref: '#/components/schemas/Film'
        salle:
          type: object
          $ref: '#/components/schemas/Salle'
        heure_diffusion:
          type: string
          format: date_time
          example: 12:00A
